name: fast_slow_server

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.0.0
  functions_framework: ^0.4.1
  google_cloud: ^0.2.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.1.0
  http: ^1.0.0
  jose: ^0.3.0
  json_annotation: ^4.3.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  stack_trace: ^1.10.0
  stats: ^2.1.0
  vote: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.4
  dart_flutter_team_lints: ^2.0.0
  json_serializable: ^6.0.0
  shelf_router_generator: ^1.0.0
  test: ^1.17.10
